server:
  port: ${port:8082}

spring:
  datasource:
    # Using in memory database
    url: jdbc:h2:mem:account-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.path: /h2-console
    console.enabled: true

eureka: #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: ${discovery.server.url}

